apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-studentXX ## replace XX with your student ID
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/sharedfolder/studentXX ## replace XX with your student ID
    server: 10.62.86.11
