apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-rolling
  labels:
    name: hello-rolling
spec:
  replicas: 3
  selector:
    matchLabels:
      name: hello-rolling
  template:
    metadata:
      labels:
        name: hello-rolling
    spec:
      containers:
      - name: hello-rolling
        image: openshift/hello-openshift
        ports:
        - containerPort: 8080